keep errno value in Error enum
My goal is to make code calling uncompress_archive to distinguish No
space left on device from other error conditions. This is related to
https://github.com/OSSystems/compress-tools-rs/issues/143 .

With this change, the error goes from:

```
thread 'main' (1282548) panicked at src/main.rs:8:63:
called `Result::unwrap()` on an `Err` value: Extraction("Can't create '/tmp/foo/make-4.4.1/NEWS'")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

to

```
thread 'main' (1287751) panicked at src/main.rs:8:63:
called `Result::unwrap()` on an `Err` value: ExtractionIo { code: Os { code: 28, kind: StorageFull, message: "No space left on device" }, details: "Can't create '/tmp/foo/make-4.4.1/NEWS'" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

which is much more explanatory. Besides, calling code can now inspect
the cause of the error:
```
if let Err(e) = uncompress_archive(&mut source, &dest, Ownership::Ignore) {
      if let Some(ioerror) =  e.source().and_then(|s| s.downcast_ref::<std::io::Error>()) {
          if ioerror.kind() == std::io::ErrorKind::StorageFull {
              println!("detected storage full")
          }
      }
  }
```

Fixes: https://github.com/OSSystems/compress-tools-rs/issues/143