error: Use inner display implementation for stdlib errors
We rely on std::io::Error and std::str::Utf8Error standard display
implementation instead of custom ones.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>