error: Change error enum names to more meaninful ones
The following errors were renamed as:

  - `ExtractionError` to `Extract`
  - `ArchiveNull` to `NullArchive`
  - `EntryNull` to `NullEntry`

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>